// Generated by https://quicktype.io


export interface MedicalResponse {
    count: number;
    next: string;
    previous: null;
    results: Professional[];
}

export interface Professional {
    id: number;
    profile_image: string;
    first_name: string;
    last_name: string;
    email: string;
    is_active: boolean;
}


export interface ProfesionalLenguajes {
    id: number;
    professional: Professional;
    language: Lenguajes;
    created_at: Date;
    modified_at: Date;
}


export interface Lenguajes {
    id: number;
    name: string;
    code: string;
    is_active: boolean;
}
